create table clubs
(
    id         bigint generated by default as identity primary key,
    name       varchar(100)             not null unique,
    active     boolean                  not null default true,
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp
);

create table rooms
(
    id          bigint generated by default as identity primary key,
    room_number varchar(20)              not null unique,
    name        varchar(100)             not null,
    active      boolean                  not null default true,
    created_at  timestamp with time zone not null default current_timestamp,
    updated_at  timestamp with time zone not null default current_timestamp
);

insert into rooms (room_number, name)
values ('321', '321호'),
       ('322', '322호');