create table users
(
    id            bigint generated by default as identity primary key,
    club_id       bigint,
    login_id      varchar(50)              not null unique,
    password_hash varchar(255)             not null,
    name          varchar(100)             not null,
    role          varchar(20)              not null,
    active        boolean                  not null default true,
    created_at    timestamp with time zone not null default current_timestamp,
    updated_at    timestamp with time zone not null default current_timestamp,

    constraint fk_users_club
        foreign key (club_id)
            references clubs (id),

    constraint chk_users_role
        check (role in ('MEMBER', 'ADMIN')),

    constraint chk_member_has_club
        check (role = 'ADMIN' or club_id is not null)
);

create index idx_users_club_id
    on users (club_id);