create extension if not exists btree_gist;

create table reservations
(
    id                  bigint generated by default as identity primary key,
    requester_id        bigint                   not null,
    club_id             bigint                   not null,
    room_id             bigint                   not null,

    type                 varchar(20)              not null,
    status               varchar(20)              not null,

    start_at             timestamp with time zone not null,
    end_at               timestamp with time zone not null,
    usage_month          date                     not null,

    requested_at         timestamp with time zone not null default current_timestamp,
    updated_at           timestamp with time zone not null default current_timestamp,

    decided_at           timestamp with time zone,
    decided_by_user_id   bigint,
    rejection_reason     varchar(500),

    canceled_at          timestamp with time zone,
    displaced_at         timestamp with time zone,
    displaced_by_id      bigint,

    constraint fk_reservations_requester
        foreign key (requester_id) references users (id),

    constraint fk_reservations_club
        foreign key (club_id) references clubs (id),

    constraint fk_reservations_room
        foreign key (room_id) references rooms (id),

    constraint fk_reservations_decider
        foreign key (decided_by_user_id) references users (id),

    constraint fk_reservations_displaced_by
        foreign key (displaced_by_id) references reservations (id),

    constraint chk_reservation_type
        check (type in ('REGULAR', 'STANDBY')),

    constraint chk_reservation_status
        check (
            status in (
                       'PENDING',
                       'APPROVED',
                       'REJECTED',
                       'CANCELED',
                       'DISPLACED',
                       'EXPIRED',
                       'COMPLETED',
                       'VOIDED'
                )
            ),

    constraint chk_reservation_time_order
        check (end_at > start_at),

    constraint chk_reservation_duration
        check (
            extract(epoch from (end_at - start_at))
                in (3600, 7200, 10800)
            ),

    constraint chk_reservation_start_hour
        check (date_trunc('hour', start_at) = start_at),

    constraint chk_reservation_end_hour
        check (date_trunc('hour', end_at) = end_at),

    constraint chk_usage_month_first_day
        check (extract(day from usage_month) = 1)
);

create index idx_reservations_requester
    on reservations (requester_id);

create index idx_reservations_club_month
    on reservations (club_id, usage_month);

create index idx_reservations_room_time
    on reservations (room_id, start_at, end_at);

alter table reservations
    add constraint ex_reservations_active_time_overlap
    exclude using gist
    (
        room_id with =,
        tstzrange(start_at, end_at, '[)') with &&
    )
    where (status in ('PENDING', 'APPROVED'));