create table club_monthly_quotas
(
    id             bigint generated by default as identity primary key,
    club_id        bigint                   not null,
    usage_month    date                     not null,
    quota_minutes  bigint                   not null,
    created_at     timestamp with time zone not null default current_timestamp,
    updated_at     timestamp with time zone not null default current_timestamp,

    constraint fk_monthly_quota_club
        foreign key (club_id) references clubs (id),

    constraint uk_monthly_quota_club_month
        unique (club_id, usage_month),

    constraint chk_quota_month_first_day
        check (extract(day from usage_month) = 1),

    constraint chk_quota_positive
        check (
            quota_minutes > 0
                and mod(quota_minutes, 60) = 0
            )
);

create table reservation_monthly_usage
(
    reservation_id bigint not null,
    usage_month    date   not null,
    usage_minutes  bigint not null,

    constraint pk_reservation_monthly_usage
        primary key (reservation_id, usage_month),

    constraint fk_monthly_usage_reservation
        foreign key (reservation_id)
            references reservations (id)
            on delete cascade,

    constraint chk_monthly_usage_first_day
        check (extract(day from usage_month) = 1),

    constraint chk_monthly_usage_positive
        check (
            usage_minutes > 0
                and mod(usage_minutes, 60) = 0
            )
);

create index idx_monthly_usage_month
    on reservation_monthly_usage (usage_month);

insert into reservation_monthly_usage
(
    reservation_id,
    usage_month,
    usage_minutes
)
select
    r.id,
    date_trunc(
            'month',
            (slot_time at time zone 'Asia/Seoul')
                - interval '7 hours'
    )::date,
    count(*) * 60
from reservations r
         cross join lateral generate_series(
    r.start_at,
    r.end_at - interval '1 hour',
                                            interval '1 hour'
    ) as slot_time
group by
    r.id,
    date_trunc(
    'month',
    (slot_time at time zone 'Asia/Seoul')
    - interval '7 hours'
    )::date;